// PROJECT MANAGER
import shafa from "@/public/assets/images/about-us/committee/shafa.webp";

// DEPUTY PROJECT MANAGER
// import taqi from "@/public/assets/images/about-us/committee/taqi.jpg";
import taqi from "@/public/assets/images/about-us/committee/taqi.jpg";
import adel from "@/public/assets/images/about-us/committee/adel.webp";
import risma from "@/public/assets/images/about-us/committee/risma.webp";

// ASISTANT PROJECT MANAGER (EVENT)
import salysia from "@/public/assets/images/about-us/committee/salysia.jpg";
import ghandi from "@/public/assets/images/about-us/committee/gandhi.webp";
import manda from "@/public/assets/images/about-us/committee/manda.webp";
import jp from "@/public/assets/images/about-us/committee/jp.webp";
import ronald from "@/public/assets/images/about-us/committee/ronald.webp";

// ASISTANT PROJECT MANAGER (GENERAL)
import sabina from "@/public/assets/images/about-us/committee/shabina.jpg";
import abdul from "@/public/assets/images/about-us/committee/abdul.webp";
import faiz from "@/public/assets/images/about-us/committee/faiz.webp";
import rafli from "@/public/assets/images/about-us/committee/rafli.webp";
import feby from "@/public/assets/images/about-us/committee/feby.webp";

// ASISTANT PROJECT MANAGER (ADVERTISE AND PHARNERSHIP)
import alawi from "@/public/assets/images/about-us/committee/alawi.webp";
import azkia from "@/public/assets/images/about-us/committee/azkiya.webp";
import azka from "@/public/assets/images/about-us/committee/azka.webp";
import adin from "@/public/assets/images/about-us/committee/adin.webp";
import zalma from "@/public/assets/images/about-us/committee/salma.webp";
import { StaticImageData } from "next/image";

// creator
import adelin from "@/public/assets/images/about-us/creator/panit2023/adeline.jpg";
import bisyr from "@/public/assets/images/about-us/creator/panit2023/bisyr.jpg";
import abija from "@/public/assets/images/about-us/creator/panit2023/abija.jpg";
import camel from "@/public/assets/images/about-us/creator/panit2023/camel.jpg";
import duhan from "@/public/assets/images/about-us/creator/panit2023/duhan.jpg";
import govin from "@/public/assets/images/about-us/creator/panit2023/govin.jpg";
import hansen from "@/public/assets/images/about-us/creator/panit2023/hansen.jpg";
import jeplin from "@/public/assets/images/about-us/creator/panit2023/jeplin.jpg";
import syafira from "@/public/assets/images/about-us/creator/panit2023/syafira.jpg";
import nirvana from "@/public/assets/images/about-us/creator/panit2023/nirvana.jpg";

import rafi from "@/public/assets/images/about-us/creator/IT/rafi.jpg";
import rehan from "@/public/assets/images/about-us/creator/IT/rehan.jpg";
import rangga from "@/public/assets/images/about-us/creator/IT/rangga.jpg";
import iyan from "@/public/assets/images/about-us/creator/IT/iyan.jpg";
import pancar from "@/public/assets/images/about-us/creator/IT/pancar.jpg";
import afzal from "@/public/assets/images/about-us/creator/IT/afzal.jpg";
import heni from "@/public/assets/images/about-us/creator/IT/heni.jpg";
import hawra from "@/public/assets/images/about-us/creator/IT/aura.jpg";

import albert from "@/public/assets/images/about-us/creator/Entertaint/albert.jpg";
import beby from "@/public/assets/images/about-us/creator/Entertaint/beby.jpg";
import dian from "@/public/assets/images/about-us/creator/Entertaint/dian.jpg";
import farhani from "@/public/assets/images/about-us/creator/Entertaint/farhani.jpg";
import jihan from "@/public/assets/images/about-us/creator/Entertaint/jihan.jpg";
import fira from "@/public/assets/images/about-us/creator/Entertaint/fira.jpg";
import johannes from "@/public/assets/images/about-us/creator/Entertaint/johannes.jpg";
import joshua from "@/public/assets/images/about-us/creator/Entertaint/joshua.jpg";
import mamay from "@/public/assets/images/about-us/creator/Entertaint/mamay.jpg";
import tegar from "@/public/assets/images/about-us/creator/Entertaint/tegar.jpg";

import user from "@/public/assets/images/about-us/avatar-placeholder.png";

export interface DPMItem {
  id: number;
  name: string;
  role: string;
  image: StaticImageData;
  description?: string;
  member?: string[];
  position?: string[];
}

export interface APMItem {
  id: number;
  name: string;
  role: string;
  member?: string;
  // image: StaticImageData;
}

export const DPM: DPMItem[] = [
  {
    id: 1,
    name: "Taqiyya Hasya Tsabitha",
    role: "Deputy Event Manager",
    image: taqi,
  },
  {
    id: 2,
    name: "Adelia Putri Handayani",
    role: "Deputy Manager for Advertising & Partnership",
    image: adel,
  },
  {
    id: 3,
    name: "Risma Akhwat",
    role: "Deputy General Manager",
    image: risma,
  },
];

export const APM: DPMItem[] = [
  // EVENT
  {
    id: 1,
    name: "Salysia Manif Fatiha",
    role: "Dept. Debate",
    image: salysia,
    description:
      "The Debate Department is responsible for organizing, managing, and overseeing debate-related activities and events.",
    member: [
      "Salysia Manif Fatiha",
      "Leila Alysia Syafiiqoh",
      "Muhammad Mario Anthony Putra Defan",
      "Vinore Deslar",
      "Naura Rushalina",
      "Tri Indah Pratiwi",
      "Alica Nurmalinda Yasmin",
      "Muhammad Zendi Alfarizi",
      "Rakka Fengary Sakkay",
      "Izka Azkiyah Arsid",
      "Geani Fatma Harris",
      "Restu Hastuti",
      "Rafa Haifasyah",
      "Windy Fauziah",
      "Nabila Salma",
      "Syasa Aulia Rasyidin",
      "Yunita Permatasari",
      "Novita iza fitri",
      "Kharisma Nurayu Afidah",
      "Kurnia Puji Astuti",
      "Ginora Marsia Noli",
      "Annisa Fitriana",
      "Adinda Salsa Aryadi Putri",
      "Alda Rizka Nurhaliza",
      "Anggun Tri Handayanti",
      "Muhammad Akhdan Fawwaz Aydin",
      "Amira Rosita Fatin",
      "Asya Khairunnisa",
      "Khairizza Amaya Shaina Kustiwa",
      "Akmal Farid",
      "Micka Videliza Pinkayla",
      "Nadhira Thauriq Fatiha",
      "Rajwa Rana Amanda",
      "Hafiizh Muhammad Gibran",
      "Virgina Nur Fitriani",
      "Zahra Cantika Talita Ningrum",
      "Salsabila Mutiara Putri",
      "Andrew Gomgom Tambunan",
      "Sandrina Maharani",
      "Indy Annisa Maharani",
      "Cahyani Yulia Rahma",
      "Agung Ramadhan",
    ],
    position: [
      "Assitant Project Manager",
      "Supervisor",
      "Finance Officer",
      "Coordinator",
      "Coordinator KDBI",
      "Administration",
      "Administration",
      "Division of Registration",
      "Committee",
      "Committee Debate",
      "Comittee",
      "Comitte",
      "Committee",
      "Committee",
      "Committee",
      "Comittee",
      "Committee",
      "Committe",
      "Comitte",
      "Committee",
      "Committee",
      "Committee",
      "Committee",
      "Committee",
      "Committe",
      "Event",
      "Event",
      "Event",
      "Event",
      "Event",
      "Event",
      "Event",
      "Event",
      "Division of CAP",
      "Division of CAP",
      "CAP EDC",
      "Debate Tabulator",
      "Ethics Code",
      "Ethics Code",
      "Ethics Code",
      "Ethics Code",
      "Ethics Code",
    ],
  },
  {
    id: 2,
    name: "Rizky Wahyu Sugandhi",
    role: "Dept. Short Movie",
    image: ghandi,
    description:
      "The Short Movie Competition Department is in charge of organizing and managing all aspects of the short movie competition.",
    member: [
      "Rizky Wahyu Sugandhi",
      "Fillah Norgiawan Kusuma",
      "Ahmad Mudzakir",
      "Cahya Eka Kartini",
      "Delia Nur Hanifah",
      "Demytri Sulistyadi Wibowo",
      "Aura Aulia Alkhomisi",
      "Vina Amelia Kurnianti",
      "Septya Kurnia Azzahra",
      "Dita Sekar Ayu Atmadi",
      "Ananda Muhammad Farid",
      "Syahrani Bunga Fitria",
      "Luh Putu Djasmine Chrystie Prabavaty",
      "Nadia Shatry",
      "Rafi Damara Putra Anggara",
      "Imelda",
      "Chairunnisa Salsabila",
      "Muhammad Rifqi",
      "Pipit Prabawati",
    ],
    position: [
      "Assistant Project Manager",
      "Supervisor",
      "Coordinator",
      "Financial Officer",
      "Administration",
      "Administration",
      "Registration",
      "Registration",
      "Registration",
      "Division of Event",
      "Division of Event",
      "Division of Event",
      "Division of Event",
      "Division of Event",
      "Division of Event",
      "Division of CAP",
      "Division of CAP",
      "Division of CAP",
      "Tabulator Short Movie",
    ],
  },
  {
    id: 3,
    name: "Almanda Fatimah Azzahra",
    role: "Dept. Scientific Paper Competition",
    image: manda,
    description:
      "The Scientific Paper Competition Department is responsible for organizing and managing events focused on academic writing and research presentation.",
    member: [
      "Almanda Fatimah Azzahra",
      "Nazwa Priyandini Cahyani Putri",
      "Shava Tasya Camelia",
      "Andhika Pratama",
      "Andi Muhammad Rivai",
      "Alfi Savio Rasyad",
      "Muhammad Hammam Gifary",
      "Muhammad Hafids",
      "Fany Handayani Rahmawati",
      "Melizha Dwi Putri",
      "Tisya Salsabrina",
      "Putri Ayu Raga Sukma",
      "Damita Alifiah Radinka",
      "Aura Savira",
      "Bima Putra Surya Pranata",
      "Muhammad Kahfi Rasyad",
      "Shafa Aulia Rahma",
      "Aisyah Nur Oktaviani",
      "Khansa Zakiyah",
      "Ayu Septiani Fauziyah",
      "Anastasya Putri Maharani",
      "Nayla Luthfia Hayati",
    ],
    position: [
      "Assistan Project Manager",
      "Supervisi",
      "Finance Officer",
      "Koordinator",
      "PJ Event Scientific Paper Competition",
      "division of event",
      "division of event",
      "division of event",
      "division of event",
      "division of event",
      "division of event",
      "division of event",
      "PJ Administration",
      "Administration",
      "PJ Kode Etik",
      "Ethic Code",
      "PJ CAP",
      "CAP",
      "CAP",
      "PJ Registration",
      "registration",
      "registration",
    ],
  },
  {
    id: 4,
    name: "Raihan Zhafran Prayogi",
    role: "Dept. International Seminar",
    image: jp,
    description:
      "The International Seminar Department is tasked with organizing high-quality seminars that bring together experts, professionals, and participants from diverse backgrounds to discuss global issues, share knowledge, and inspire innovation.",
    member: [
      "Raihan Zhafran Prayogi",
      "Putri Ferina",
      "Tasya Dwi Melani",
      "Muhammad Hanif",
      "Ananta Azzahra",
      "Shefiana Dhifta Yudha Octavia",
      "Firly Aulia Achmad",
      "Labib Qinthara Ramadhan",
      "Istiqomah Suci Fajariani",
      "Mayang Putri Rengganis",
      "Rendy Putra Pratama",
      "Hanna Melya Putri Whadana",
      "Atha Fadhil Ernowo",
      "Claura Tri Rispriatina",
      "Adinda Damayanty",
      "Cicilia Meiliani",
      "Neng Sopia Pida Hubaiba",
      "Maizahra Cahyani",
    ],
    position: [
      "Assistant Project Manager",
      "Supervisor",
      "Coordinator",
      "Financial Officer",
      "Administration",
      "Administration",
      "PJ Registration",
      "Registration",
      "PJ Division of Event",
      "Division of Event",
      "Division of Event",
      "Division of Event",
      "Division of Event",
      "Division of Event",
      "Division of Event",
      "PJ Division of CSP",
      "Division of CSP",
      "Division of CSP",
    ],
  },
  {
    id: 5,
    name: "Ronald Lakhomizaro Gulo",
    role: "Dept. Entertainment",
    image: ronald,
    description:
      "The Entertainment Department is responsible for organizing and managing all entertainment-related activities for events.",
    member: [
      "Ronald Lakhomizaro Gulo",
      "Farhani Kurniayu",
      "Anisa Salsabila",
      "Nayla Regita Naswar",
      "Joshua Pratama Martinus",
      "Johanes Nathanael Bimambang",
      "Albert Deniel Sitorus",
      "Beby Alya Rahman Nasution",
      "Dwi Indah Pramudita Wati",
      "Az-zahra Revalina Pramudhita",
      "Bernice Bernadeth",
      "Elisa Maria Yuliana",
      "Zika Aqlia Rhomanhova",
      "Meuthia Azzahra",
      "Afifah Nur Pyannisa",
    ],
    position: [
      "Assistant Project Manager",
      "Supervisor",
      "Finance Officer",
      "Administration",
      "Music Production",
      "Music Production",
      "Background Visual Effect",
      "Background Visual Effect",
      "MC & Moderator",
      "MC & Moderator",
      "MC & Moderator",
      "Division of Performers",
      "Division of Performers",
      "Division of Performers",
      "Division of Performers",
    ],
  },

  // GENERAL
  {
    id: 6,
    name: "Abdul Gofur",
    role: "Dept. Security",
    image: abdul,
    description:
      "The Security Department is responsible for ensuring the safety and security of all participants, guests, and assets during events.",
    member: [
      "Abdul Gofur",
      "Najmia",
      "Silvya Ajeng Rosmalianti",
      "Rizal Oktober Silitonga",
      "Rafif Yudo Prakosa",
      "Fery Irawan Sahputra.tb",
      "Rakha Hamaminata",
      "Annisa Anggraini",
      "Ailsa Shafa Adriyani",
      "Assyfa Nur Fitria",
      "Gatra Yudha Arya Winata",
      "Muhamad Dhafi Faqarasyian",
    ],
    position: [
      "Assistant Project Manager",
      "Secretary",
      "Finance Officer",
      "Patrol Team",
      "Patrol Team",
      "Patrol Team",
      "Patrol Team",
      "Patrol Team",
      "Crowd Control",
      "Crowd Control",
      "Crowd Control",
    ],
  },
  {
    id: 7,
    name: "Faiz Chalimatussa'diah",
    role: "Dept. Finance",
    image: faiz,
    description:
      "The Finance Department is responsible for managing all financial aspects of an event or organization. This includes budgeting, tracking expenses, handling transactions, and ensuring financial transparency.",
    member: [
      "Faiz Chalimatussa'diah",
      "Nabila Dea Fikriani",
      "Muhammad Akmal Baskoro",
      "Vinka Cahyani",
      "Dian Oktaviasari",
      "Wafa Ma'alim Fithoriq",
      "Fitria Apriliani",
      "Sabiila Nuur Fadhilah",
      "Putri Nabilah",
      "Harini Setyowati",
    ],
    position: [
      "Assistant Project Manager",
      "Field Treasurer",
      "Field Treasurer",
      "Field Treasurer",
      "Field Treasurer",
      "Field Treasurer",
      "Notes and Receipts",
      "Notes and Receipts",
      "Cash Bookkeeping",
      "Cash Bookkeeping",
    ],
  },
  {
    id: 8,
    name: "Alfarizky Esah Raffliansyah",
    role: "Dept. Infrastructure",
    image: rafli,
    description:
      "The Infrastructure Department is responsible for planning, organizing, and maintaining the physical resources required for events.",
    member: [
      "Alfarizky Esah Raffliansyah",
      "Cintya Ningrum",
      "Rastia Tri Septiani",
      "Rinda Alisha Putri",
      "Nisha Sabilla",
      "Muhammad Fadhilah Akbar",
      "Wisnu Hartono",
      "Dian Rivanno",
      "Salsabil Albi Fahri",
      "Agung Saputra",
      "Noor Sultan Irgi Wibowo",
      "Ridho Kurnia Akbar",
      "Fathia Az Zahra",
      "Aru Chevy Rasyid",
      "Dhevita Maharani Azzahra Hernawan",
      "I Putus Surya Agung Pratama",
      "Luvita Indah Cahyani",
      "Beni Maryana",
      "Isna Silviana",
    ],
    position: [
      "Assistant Project Manager",
      "Supervisor",
      "Finance Officer",
      "Secretary",
      "Secretary",
      "Inventory Officer",
      "Division of Facilities",
      "Division of Facilities",
      "Division of Facilities",
      "Division of Facilities",
      "Division of Facilities",
      "Division of Facilities",
      "Division of Infrastructure",
      "Division of Infrastructure",
      "Division of Infrastructure",
      "Division of Infrastructure",
      "Division of Infrastructure",
      "Division of Infrastructure",
      "Division of Infrastructure",
    ],
  },
  {
    id: 9,
    name: "Shabrina azka",
    role: "Dept. Health",
    image: sabina,
    description:
      "The Health Department is tasked with ensuring the physical well-being and safety of all committee and participants during events.",
    member: [
      "Shabrina Azka",
      "Salwa Fathimatuzzahroh",
      "Maryam",
      "Annafsul Mutmainnah",
      "Putri Allya Zahra",
      "Syva Fauziah",
      "Gisheila Asharra Fitri",
      "Vina Febriyanti",
      "Mohamad Afif",
      "Nggari Rahma Putri",
      "Melani Martiani",
      "Fajar Subekti",
    ],
    position: [
      "Assistant Project Manager",
      "Supervisor",
      "Administration & Finance",
      "Post 1 Team and Unas Clinic Team",
      "Post 2 Team",
      "Post 2 Team",
      "Controlling",
      "Controlling",
      "Controlling",
      "Controlling",
      "Controlling",
      "Controlling",
    ],
  },
  {
    id: 10,
    name: "Febiana Azhari",
    role: "Dept. F&B",
    image: feby,
    description:
      "The Food and Beverage (F&B) Department is responsible for planning, organizing, and delivering meals, snacks, and beverages during events.",
    member: [
      "Febiana Azahri",
      "Rahma Alya Fayza",
      "Azelia Safira Satya Yahya",
      "Rizka Oktaviani",
      "Tasya Aurelia",
      "Syafiya Anurrahim",
      "Elena Edelweis Iskandarmouda",
      "Anna Widyaatuti",
      "Richa Ashyllah Rahmayanti",
      "Merdhika Tri Handayani",
      "Keysha Andani",
      "Siti Sekar Ayuningsih",
      "Nanda Dwi Wahyu Bima Atmojo",
    ],
    position: [
      "Assistant Project Manager",
      "Supervisor",
      "Secretary",
      "Finance Officer",
      "VIP & Invitation",
      "VIP & Invitation",
      "VIP & Invitation",
      "Division of Committee",
      "Division of Committee",
      "Division of Committee",
      "Division of Participants",
      "Division of Participants",
      "Division of Participants",
    ],
  },

  // ADVERTISE AND PHARNERSHIP
  {
    id: 11,
    name: "Achmad Maulana Alawi",
    role: "Dept. Information Technology",
    image: alawi,
    description:
      "The Information Technology (IT) Department is responsible for designing, developing, and maintaining the digital platforms for the event, including unasfest.com and caturnawa.unasfest.com.",
    member: [
      "Achmad Maulana Alawi",
      "Hawra Fathiya Zahra",
      "M. Rangga Miftahul Falah",
      "Heni Fitriany",
      "M. Raihan Putra Febrianto",
      "Moch Rafindra Aditias",
      "Ferdiansyach",
      "Afzal Khairahman",
      "Pancar Hizkia",
    ],
    position: [
      "Assistant Project Manager",
      "Secretarial and Finance",
      "Technical Leader",
      "Technical Leader",
      "UI/UX Designer",
      "Fullstack Web Developer",
      "Fullstack Web Developer",
      "Fullstack Web Developer",
      "Fullstack Web Developer",
    ],
  },
  {
    id: 12,
    name: "Azkia Huzaima",
    role: "Dept. Public Relation",
    image: azkia,
    description:
      "The Public Relation (PR) Department is responsible for managing communication between the event organizers and the public, participants, sponsors, partners and stakeholders.",
    member: [
      "Azkia Huzaima",
      "Titis Rahmawati",
      "Shakila Azharaini",
      "Muhammad Rakha Kesuma",
      "Hafla Ratu Ainayya",
      "Hurul Aini",
      "Achmad Rizki Riyanto Ramadhan",
      "Hikma Rizky Utami",
      "Nur Hafizah",
      "Piya Syawala Dehan",
      "Widya Amelia Putri",
      "Annisa",
      "Nasya Rizka Saputri",
      "Puspita Cintya Maulida",
      "Muhammad Rayhan Vernandhi",
    ],
    position: [
      "Assistant Project Manager (APM)",
      "Supervision",
      "Financial Officer",
      "Division of Event EDC",
      "Division of Event EDC",
      "Administration",
      "Division of Event KDBI",
      "Division of Event KDBI",
      "Division of Event LKTI",
      "Division of Event LKTI",
      "Division of Event Short Movie",
      "Division of Event Short Movie",
      "Division of Event Seminar International",
      "Division of Civitas",
      "Korlap",
    ],
  },
  {
    id: 13,
    name: "Muhammad Azka Najhan",
    role: "Dept. Advertising",
    image: azka,
    description:
      "The Advertising Department is tasked with creating and executing promotional strategies to maximize event visibility and engagement.",
    member: [
      "Muhammad Azka Najhan",
      "Dwi Luvita Sari",
      "Januarizka Kamilah",
      "Muhamad Firli Ramadhan",
      "Nabila Andina",
      "Muhammad Bisyr",
      "Nirvana Putri Rizal",
      "Dessy Wahyuningsih",
      "Tsawaabulkhair",
      "Endien Stevani Susarno",
      "Arvisa Marshanda",
      "Diah Hanung Cahyani",
      "Nashwa Rifa El Syifa",
      "Aghna Fadiyah Putri",
      "Silver Christ Boyke Zai",
      "Maisaan Muzakki Ramadhan",
      "Syifa Azzahra Tuna",
      "Ratu Aldilah Kustantia",
      "Keyza Tialina Reisita Sihombing",
      "Nouval Rivaldy Baguska",
      "Aris Fadhilah Lazuardi",
    ],
    position: [
      "Assistant Project Manager",
      "Secretarial & Finance Officer",
      "Division of Graphic Design",
      "PJ Division of Graphic Design",
      "Division of Graphic Design",
      "Division of Graphic Design",
      "Division of Graphic Design",
      "PJ Division of Content Creator",
      "Division of Content Creator",
      "Division of Content Creator",
      "Division of Content Creator",
      "Division of Content Creator",
      "Division of Content Planning",
      "PJ Division of Content Planning",
      "Division of Documentary",
      "PJ Division of Documentary",
      "Division of Documentary",
      "Division of Pers",
      "PJ Division of Pers",
      "Division of Documentary",
      "Division of Documentary",
    ],
  },
  {
    id: 14,
    name: "Adinda Pramestia",
    role: "Dept. Secretarial Affairs Department",
    image: adin,
    description:
      "The Secretarial Affairs Department ensures smooth administrative operations, maintaining clear communication and documentation throughout the event planning and execution process.",
    member: [
      "Adinda Pramestia",
      "Kaisyah Cika Ramadhina",
      "Putri Nur Azizah",
      "Alma Wulan Astriasty Lomban Wullur",
      "Callysta Fauziyyah Zahran",
      "Alma Chantiqa Hadiyya Pujiandini",
      "Mufidah Aura Taqiya",
      "Luthfita Nur Anggraeni",
      "Deby Putri Ayu",
      "Putri Rahayu",
      "Rizqi Khoirunnisa Meylani Awaliah",
      "Alya Giska Alivia",
    ],
    position: [
      "Adinda Pramestia",
      "Kaisyah Cika Ramadhina",
      "Putri Nur Azizah",
      "Alma Wulan Astriasty Lomban Wullur",
      "Callysta Fauziyyah Zahran",
      "Alma Chantiqa Hadiyya Pujiandini",
      "Mufidah Aura Taqiya",
      "Luthfita Nur Anggraeni",
      "Deby Putri Ayu",
      "Putri Rahayu",
      "Rizqi Khoirunnisa Meylani Awaliah",
      "Alya Giska Alivia",
    ],
  },
  {
    id: 15,
    name: "Zalma Nabila Taufik",
    role: "Dept. Partnership",
    image: zalma,
    description:
      "The Partnership Department focuses on building and managing relationships with external organizations, partners, and sponsors.",
    member: [
      "Zalma Nabila Taufik",
      "Talitha Zafirah Maharani",
      "Woci Anistia Ain",
      "Siti Haritza Kusuma Nurdifa Ainisa",
      "Devina Putri Hasna Yuniartanti",
      "Fredrico Tamado Imanuel",
      "Alyatur Rahmah",
      "Fitri Farihatul Maziyyah",
      "Amanda Tasya Sifa Febriyanti",
      "Nanda Oktaviana",
      "Maulidatun Nazwa",
    ],
    position: [
      "Assistant Project Manager",
      "Secretarial",
      "Finance Officer",
      "Delegation of Department Partnership",
      "Delegation Sponsorship",
      "Delegation of Sponsorship",
      "Donature",
      "Media Partner",
      "Media Partner",
      "Bazar",
      "Bazar",
    ],
  },
];

export const Maskot: DPMItem[] = [
  {
    id: 1,
    name: "Adelin Vinico Yuanita",
    role: "Maskot UNAS FEST 2023 and logo UNAS FEST",
    image: adelin,
  },
  {
    id: 2,
    name: "Muhammad Bisyr",
    role: "Maskot UNAS FEST 2024",
    image: bisyr,
  },
];

export const Music: DPMItem[] = [
  {
    id: 1,
    name: "Ronald Lakhomizaro Gulo",
    role: "Producer Music",
    image: ronald,
  },
  {
    id: 2,
    name: "Syafira Fairuz",
    role: "Song Writer Anthem UNAS FEST",
    image: syafira,
  },
  {
    id: 3,
    name: "Tegar Budiman",
    role: "Song Writer Anthem UNAS FEST",
    image: tegar,
  },
  {
    id: 4,
    name: "Farhani Kurniayu",
    role: "Singer Anthem UNAS FEST",
    image: farhani,
  },
  {
    id: 5,
    name: "Alfarizky Esah Raffliansyah",
    role: "Singer Anthem UNAS FEST",
    image: rafli,
  },
  {
    id: 6,
    name: "Maimunahwaroh Heta Warman",
    role: "Singer Anthem UNAS FEST",
    image: mamay,
  },
  {
    id: 7,
    name: "Camelia Nur Hidayah",
    role: "Seminar Nasional",
    image: camel,
  },
  {
    id: 8,
    name: "Dian Sarah Purba",
    role: "Seminar Nasional",
    image: dian,
  },
  {
    id: 9,
    name: "Tegar Budiman",
    role: "Seminar Nasional",
    image: tegar,
  },
  {
    id: 10,
    name: "Nabila Shafa Sabrina",
    role: "Seminar Nasional",
    image: shafa,
  },
  {
    id: 11,
    name: "Nirvana Putri Rizal",
    role: "Dubbing Voice Over Lumina Verde",
    image: nirvana,
  },
  {
    id: 12,
    name: "Ronald Lakhomizaro Gulo",
    role: "Producer & Arranger Music",
    image: ronald,
  },
  {
    id: 13,
    name: "Joshua Pratama Martinus",
    role: "Producer & Arranger Music",
    image: joshua,
  },
  {
    id: 14,
    name: "Johanes Nathanael Bimambang",
    role: "Producer & Arranger Music",
    image: johannes,
  },
  {
    id: 15,
    name: "Albert Deniel Sitorus",
    role: "BFX",
    image: albert,
  },
  {
    id: 16,
    name: "Beby Alya Rahman Nasution",
    role: "BFX",
    image: beby,
  },
  {
    id: 17,
    name: "Jihan Fauziah",
    role: "Koreografer",
    image: jihan,
  },
];

export const Web: DPMItem[] = [
  {
    id: 1,
    name: "Achmad Maulana Alawi",
    role: "Website UNAS FEST 2024 and Caturnawa 2024",
    image: alawi,
  },
  {
    id: 2,
    name: "Muhammad Rangga Miftahul Falah",
    role: "Website UNAS FEST 2024 and Caturnawa 2024",
    image: rangga,
  },
  {
    id: 3,
    name: "Heni Fitriany",
    role: "Website UNAS FEST 2024 and Caturnawa 2024",
    image: heni,
  },
  {
    id: 4,
    name: "Hawra Fathiya Zahra",
    role: "Website UNAS FEST 2024 and Caturnawa 2024",
    image: hawra,
  },
  {
    id: 5,
    name: "Muhammad Raihan Putra Febrianto",
    role: "Website UNAS FEST 2024 and Caturnawa 2024",
    image: rehan,
  },
  {
    id: 6,
    name: "Moch Rafindra Aditias",
    role: "Website UNAS FEST 2024 and Caturnawa 2024",
    image: rafi,
  },
  {
    id: 7,
    name: "Ferdiansyach",
    role: "Website UNAS FEST 2024 and Caturnawa 2024",
    image: iyan,
  },
  {
    id: 8,
    name: "Afzal Khairahmansyach",
    role: "Website UNAS FEST 2024 and Caturnawa 2024",
    image: afzal,
  },
  {
    id: 9,
    name: "Pancar Hizkia",
    role: "Website UNAS FEST 2024 and Caturnawa 2024",
    image: pancar,
  },
  {
    id: 10,
    name: "Hansen Chandra",
    role: "Website UNAS FEST 2023",
    image: hansen,
  },
  {
    id: 11,
    name: "Ciptoningaji Guridno",
    role: "Website UNAS FEST 2023",
    image: user,
  },
  {
    id: 12,
    name: "Ronald Lakhomizaro Gulo",
    role: "Website UNAS FEST 2023",
    image: ronald,
  },
  {
    id: 13,
    name: "Rizky Wahyu Sugandhi",
    role: "Website UNAS FEST 2023",
    image: ghandi,
  },
  {
    id: 14,
    name: "Rian Hidayat",
    role: "Website UNAS FEST 2023",
    image: user,
  },
  {
    id: 15,
    name: "Abija Bohdan P.",
    role: "Website UNAS FEST 2023",
    image: abija,
  },
  {
    id: 16,
    name: "Arga Mahesa Putra",
    role: "Website UNAS FEST 2023",
    image: user,
  },
  {
    id: 17,
    name: "Govinda Marcelino",
    role: "Website UNAS FEST 2023",
    image: govin,
  },
  {
    id: 18,
    name: "Duhan Maulana Artline",
    role: "Caturnawa UANS FEST 2023",
    image: duhan,
  },
  {
    id: 19,
    name: "Jepplin Sinaga",
    role: "Caturnawa UANS FEST 2023",
    image: jeplin,
  },
];
