import type { Metadata } from "next";
import { Bungee, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/(HOME)/Navbar/Navbar";
import Footer from "@/components/shared/(HOME)/Footer/Footer";

const bungee = Bungee({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-bungee",
  display: "swap",
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${bungee.variable} bg-[#FFFAF0] overflow-x-hidden`}
      >
        {/* Navbar */}
        <Navbar />
        {children}
        {/* Footer */}
        <Footer />
      </body>
    </html>
  );
}
