export const timelinesHome = [
  {
    title: "Opening Registration UNAS FEST 2024 ",
    description:
      "Opening registration of UNAS FEST 2024 competition debate, short movie, and scientific paper competition",
    month: "JULY",
    date: "23",
    year: "2024",
    color: "#2A9763",
  },
  {
    title: "Opening registration of UNAS FEST 2024 International Seminar",
    description: "Opening registration of UNAS FEST 2024 International Seminar",
    month: "AUG",
    date: "12",
    year: "2024",
    color: "#1F1E23",
  },
  {
    title: "Administration Selection and Assessment of Short Movie Participants' Outstanding Achievements",
    description: "The administrative selection process and assessment of outstanding achievements for Short Movie participants",
    month: "AUG",
    date: "23",
    year: "2024",
    color: "#1F1E23",
  },
  {
    title: "Preliminary of SPC",
    description: "This round marks the initial phase of the SPC",
    month: "AUG",
    date: "23",
    year: "2024",
    color: "#1F1E23",
  },
  {
    title: "International Seminar",
    description: "International Seminar Day",
    month: "SEP",
    date: "17",
    year: "2024",
    color: "#1F1E23",
  },
  {
    title: "Preliminary of KDBI and EDC",
    description: "The preliminary for KDBI and EDC competitions",
    month: "SEP",
    date: "18",
    year: "2024",
    color: "#1F1E23",
  },
  {
    title: "Preliminary of Short Movie",
    description: "The preliminary for Short Movie",
    month: "SEP",
    date: "28",
    year: "2024",
    color: "#1F1E23",
  },
  {
    title: "Finals of UNAS FEST 2024 SPC, Debate, and Short Movie Competition",
    description: "SPC, Debate, and Short Movie Competition Finalist",
    month: "OKT",
    date: "14",
    year: "2024",
    color: "#1F1E23",
  },
  {
    title: "Finals of UNAS FEST 2024 SPC and Short Movie Competition",
    description: "SPC and Short Movie Competition Finalist",
    month: "OKT",
    date: "15",
    year: "2024",
    color: "#1F1E23",
  },
];

export const timelinesEDC = [
  {
    title: "Open Registration EDC",
    description: "Open Registration for English Debate Competition",
    month: "JULY",
    date: "23",
    year: "2024",
    color: "#004AAD",
  },
  {
    title: "Close Registration EDC",
    description: "Open Registration for English Debate Competition",
    month: "DEC",
    date: "23",
    year: "2024",
    color: "#004AAD",
  },
  {
    title: "Technical Meeting for EDC Participants",
    description:
      "Important Information for Participants about Competition Rules",
    month: "SEP",
    date: "6",
    year: "2024",
    color: "#004AAD",
  },
  {
    title: "Preliminary Round 1 of EDC",
    description: "This round marks the initial phase of the EDC",
    month: "SEP",
    date: "18",
    year: "2024",
    color: "#004AAD",
  },
  {
    title: "Preliminary Round 2 of EDC",
    description: "This round marks the initial phase of the EDC",
    month: "SEP",
    date: "19",
    year: "2024",
    color: "#004AAD",
  },
  {
    title: "EDC Semi-Final Round",
    description: "to get a chance to advance to the final round",
    month: "SEP",
    date: "20",
    year: "2024",
    color: "#004AAD",
  },
  {
    title: "Finalists attend Technical Meeting",
    description: "Finalists attend the Technical Meeting in order to be informed about the mechanism of dabate",
    month: "OCT",
    date: "5",
    year: "2024",
    color: "#004AAD",
  },
  {
    title: "Final Day 1 Kompetisi English Debate Competition",
    description: "The final stage to determine who will be the winner",
    month: "OCT",
    date: "16",
    year: "2024",
    color: "#004AAD",
  },
  {
    title: "Final Day 2 Kompetisi English Debate Competition",
    description: "The final stage to determine who will be the winner",
    month: "OCT",
    date: "17",
    year: "2024",
    color: "#004AAD",
  },
];

export const timelinesKDBI = [
  {
    title: "Open Registration KDBI",
    description: "Open Registration for KDBI",
    month: "JULY",
    date: "23",
    year: "2024",
    color: "#2A9763",
  },
  {
    title: "Close Registration KDBI",
    description: "Close Registration for KDBI",
    month: "AUGUST",
    date: "23",
    year: "2024",
    color: "#2A9763",
  },
  {
    title: "Technical Meeting for KDBI Participants",
    description:
      "Important Information for Participants about Competition Rules",
    month: "SEP",
    date: "6",
    year: "2024",
    color: "#2A9763",
  },
  {
    title: "Preliminary Round 1 of KDBI",
    description: "This round marks the initial phase of the KDBI",
    month: "SEP",
    date: "18",
    year: "2024",
    color: "#2A9763",
  },
  {
    title: "Preliminary Round 2 of KDBI",
    description: "This round marks the initial phase of the KDBI",
    month: "SEP",
    date: "19",
    year: "2024",
    color: "#2A9763",
  },
  {
    title: "KDBI Semi-Final Round",
    description: "to get a chance to advance to the final round",
    month: "SEP",
    date: "20",
    year: "2024",
    color: "#2A9763",
  },
  {
    title: "Finalists attend Technical Meeting",
    description: "Finalists attend the Technical Meeting in order to be informed about the mechanism of dabate",
    month: "OCT",
    date: "5",
    year: "2024",
    color: "#2A9763",
  },
  {
    title: "Final Day 1 KDBI",
    description: "The final stage to determine who will be the winner",
    month: "OCT",
    date: "16",
    year: "2024",
    color: "#2A9763",
  },
  {
    title: "Final Day 2 KDBI",
    description: "The final stage to determine who will be the winner",
    month: "OCT",
    date: "17",
    year: "2024",
    color: "#2A9763",
  },
];

export const timelinesSMC = [
  {
    title: "Open Registration SMC",
    description: "Open Registration for SMC",
    month: "JULY",
    date: "23",
    year: "2024",
    color: "#C02424",
  },
  {
    title: "Close Registration SMC",
    description: "Close Registration for SMC",
    month: "AUGUST",
    date: "23",
    year: "2024",
    color: "#C02424",
  },
  {
    title: "Submission of Short Movie Videos is open",
    description:
      "the process of submitting short film competition videos is ongoing or has just open",
    month: "JULY",
    date: "23",
    year: "2024",
    color: "#C02424",
  },
  {
    title: "Submission of Short Movie Videos is closed",
    description:
      "the process of submitting short film competition videos is ongoing or has just close",
    month: "SEP",
    date: "27",
    year: "2024",
    color: "#C02424",
  },
  {
    title: "Beginning of the Preliminary Round of Short Movie",
    description: "The process of submitting Short Movie Videos is open",
    month: "SEP",
    date: "27",
    year: "2024",
    color: "#C02424",
  },
  {
    title: "End of the Preliminary Round of Short Movie",
    description: "The process of submitting Short Movie Videos is close",
    month: "SEP",
    date: "28",
    year: "2024",
    color: "#C02424",
  },
  {
    title: "Semifinal Round of Short Movie",
    description: "To determine which films will advance to the final round",
    month: "SEP",
    date: "30",
    year: "2024",
    color: "#C02424",
  },
  {
    title: "Announcement of Finalists of the Short Movie Competition",
    description: "Announcing the finalists who advance to the final round",
    month: "OCT",
    date: "1",
    year: "2024",
    color: "#C02424",
  },
  {
    title: "Participants' Technical Meeting",
    description:
      "Important Information for Participants about Competition Rules",
    month: "OCT",
    date: "5",
    year: "2024",
    color: "#C02424",
  },
  {
    title: "Final Day 1 SMC",
    description: "The final stage to determine who will be the winner",
    month: "OCT",
    date: "16",
    year: "2024",
    color: "#C02424",
  },
  {
    title: "Final Day 2 SMC",
    description: "The final stage to determine who will be the winner",
    month: "OCT",
    date: "17",
    year: "2024",
    color: "#C02424",
  },
];

export const timelinesSPC = [
  {
    title: "Open Registration SPC",
    description: "Open Registration for SPC",
    month: "JULY",
    date: "23",
    year: "2024",
    color: "#E27817",
  },
  {
    title: "Close Registration SPC",
    description: "Close Registration for SPC",
    month: "AUGUST",
    date: "23",
    year: "2024",
    color: "#E27817",
  },
  {
    title: "Preliminary of SPC",
    description: "This round marks the initial phase of the SPC",
    month: "SEP",
    date: "23",
    year: "2024",
    color: "#E27817",
  },
  {
    title: "Announcement of Passing the Administrative Selection",
    description:
      "Official announcement informing that they have successfully passed the administrative selection stage",
    month: "AUG",
    date: "27",
    year: "2024",
    color: "#E27817",
  },

  {
    title: "The access for submitting or sending SPC manuscripts is open",
    description: "Opening of the submission or delivery of SPC manuscripts",
    month: "AUG",
    date: "28",
    year: "2024",
    color: "#E27817",
  },
  {
    title: "The access for submitting or sending SPC manuscripts is close",
    description: "Closing of the submission or delivery of SPC manuscripts",
    month: "SEP",
    date: "11",
    year: "2024",
    color: "#E27817",
  },
  {
    title: "The announcement of the 6 finalists of SPC",
    description:
      "The announcement of the 6 finalists of SPC proceeding to the next round",
    month: "SEP",
    date: "24",
    year: "2024",
    color: "#E27817",
  },
  {
    title: "Participants' Technical Meeting",
    description:
      "Important Information for Participants about Competition Rules",
    month: "OCT",
    date: "5",
    year: "2024",
    color: "#E27817",
  },
  {
    title: "Final Scientific Paper Competition",
    description: "The final stage to determine who will be the winner",
    month: "OCT",
    date: "17",
    year: "2024",
    color: "#E27817",
  },
];

export const timelinesSemnas = [
  {
    title: "Open Registration for the National Seminar UNAS FEST 2024",
    description:
      "Registration for the National Seminar at UNAS FEST 2024 is now open! Join students, academics, and professionals.",
    month: "AUG",
    date: "12",
    year: "2024",
    color: "#853EB6",
  },
  {
    title: "Close Registration for the National Seminar UNAS FEST 2024",
    description:
      "Registration for the National Seminar at UNAS FEST 2024 is now close! Join students, academics, and professionals.",
    month: "SEP",
    date: "13",
    year: "2024",
    color: "#853EB6",
  },
  {
    title: "International Seminar",
    description: "International Seminar Day",
    month: "SEP",
    date: "17",
    year: "2024",
    color: "#853EB6",
  },
];
